export const ADD_BATCH = 'ADD_BATCH';
export const EDIT_BATCH = 'EDIT_BATCH';
export const DELETE_BATCH = 'DELETE_BATCH';
export const BATCHES_LOADING = 'BATCHES_LOADING';
export const BATCHES_FAILED = 'BATCHES_FAILED';
export const BATCHES_SUCCESS = 'BATCHES_SUCCESS';

export const BATCH_LOADING = 'BATCH_LOADING';
export const BATCH_FAILED = 'BATCH_FAILED';
export const BATCH_SUCCESS = 'BATCH_SUCCESS';

export const ADD_MEETING = 'ADD_MEETING';
export const EDIT_MEETING = 'EDIT_MEETING';
export const DELETE_MEETING = 'DELETE_MEETING';

export const ADD_STUDENT_IN_BATCH = 'ADD_STUDENT_IN_BATCH';
export const STUDENT_IN_BATCH_LOADING = 'STUDENT_IN_BATCH_LOADING';
export const STUDENT_IN_BATCH_FAILED = 'STUDENT_IN_BATCH_FAILED';
export const STUDENT_IN_BATCH_SUCCESS = 'STUDENT_IN_BATCH_SUCCESS';
export const DELETE_STUDENT_FROM_BATCH = 'DELETE_STUDENT_FROM_BATCH';

export const ADD_SEMESTER = 'ADD_SEMESTER';
export const EDIT_SEMESTER = 'EDIT_SEMESTER';
export const DELETE_SEMESTER = 'DELETE_SEMESTER';
export const SEMESTER_LOADING = 'SEMESTER_LOADING';
export const SEMESTER_FAILED = 'SEMESTER_FAILED';

export const ADD_INTERNSHIP = 'ADD_INTERNSHIP';
export const EDIT_INTERNSHIP = 'EDIT_INTERNSHIP';
export const DELETE_INTERNSHIP = 'DELETE_INTERNSHIP';

export const ADD_COURSE = 'ADD_COURSE';
export const EDIT_COURSE = 'EDIT_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';

export const ADD_RESULT = 'ADD_RESULT';
export const EDIT_RESULT = 'EDIT_RESULT';
export const DELETE_RESULT = 'DELETE_RESULT';

export const ADD_ABSENCE = 'ADD_ABSENCE';
export const DELETE_ABSENCE = 'DELETE_ABSENCE';

export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';

export const TEACHER_LOGIN_REQUEST = 'TEACHER_LOGIN_REQUEST';
export const TEACHER_LOGIN_SUCCESS = 'TEACHER_LOGIN_SUCCESS';
export const TEACHER_LOGIN_FAILURE = 'TEACHER_LOGIN_FAILURE';
export const TEACHER_LOGOUT_REQUEST = 'TEACHER_LOGOUT_REQUEST';
export const TEACHER_LOGOUT_SUCCESS = 'TEACHER_LOGOUT_SUCCESS';
export const TEACHER_LOGOUT_FAILURE = 'TEACHER_LOGOUT_FAILURE';

export const STUDENT_LOGIN_REQUEST = 'STUDENT_LOGIN_REQUEST';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAILURE = 'STUDENT_LOGIN_FAILURE';
export const STUDENT_LOGOUT_REQUEST = 'STUDENT_LOGOUT_REQUEST';
export const STUDENT_LOGOUT_SUCCESS = 'STUDENT_LOGOUT_SUCCESS';
export const STUDENT_LOGOUT_FAILURE = 'STUDENT_LOGOUT_FAILURE';

export const REDIRECT = "REDIRECT";
export const REMOVE_REDIRECT = "REMOVE_REDIRECT";

export const MESSAGE = "MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";

export const TEACHER_PROFILE_LOADING = "TEACHER_PROFILE_LOADING";
export const TEACHER_PROFILE_SUCCESS = "TEACHER_PROFILE_SUCCESS";
export const TEACHER_PROFILE_FAILED = "TEACHER_PROFILE_FAILED";

export const STUDENT_PROFILE_LOADING = "STUDENT_PROFILE_LOADING";
export const STUDENT_PROFILE_SUCCESS = "STUDENT_PROFILE_SUCCESS";
export const STUDENT_PROFILE_FAILED = "STUDENT_PROFILE_FAILED";

export const INTERNSHIP_CERTIFICATE_LOADING = "INTERNSHIP_CERTIFICATE_LOADING";
export const INTERNSHIP_CERTIFICATE_SUCCESS = "INTERNSHIP_CERTIFICATE_SUCCESS";
export const INTERNSHIP_CERTIFICATE_FAILED = "INTERNSHIP_CERTIFICATE_FAILED";

export const RESULT_LOADING = "RESULT_LOADING";
export const RESULT_SUCCESS = "RESULT_SUCCESS";
export const RESULT_FAILED = "RESULT_FAILED";

export const SUBJECTS_LOADING = "SUBJECTS_LOADING";
export const SUBJECTS_SUCCESS = "SUBJECTS_SUCCESS";
export const SUBJECTS_FAILED = "SUBJECTS_FAILED";

export const SUBJECT_LOADING = "SUBJECT_LOADING";
export const SUBJECT_SUCCESS = "SUBJECT_SUCCESS";
export const SUBJECT_FAILED = "SUBJECT_FAILED";