export const ADD_BATCH = 'ADD_BATCH';
export const EDIT_BATCH = 'EDIT_BATCH';
export const DELETE_BATCH = 'DELETE_BATCH';
export const BATCH_LOADING = 'BATCH_LOADING';
export const BATCH_FAILED = 'BATCH_FAILED';

export const ADD_MEETING = 'ADD_MEETING';
export const EDIT_MEETING = 'EDIT_MEETING';
export const DELETE_MEETING = 'DELETE_MEETING';
export const MEETING_LOADING = 'MEETING_LOADING';
export const MEETING_FAILED = 'MEETING_FAILED';

export const ADD_STUDENT_IN_BATCH = 'ADD_STUDENT_IN_BATCH';
export const STUDENT_IN_BATCH_LOADING = 'STUDENT_IN_BATCH_LOADING';
export const STUDENT_IN_BATCH_FAILED = 'STUDENT_IN_BATCH_FAILED';
export const DELETE_STUDENT_FROM_BATCH = 'DELETE_STUDENT_FROM_BATCH';

export const ADD_SEMESTER = 'ADD_SEMESTER';
export const EDIT_SEMESTER = 'EDIT_SEMESTER';
export const DELETE_SEMESTER = 'DELETE_SEMESTER';
export const SEMESTER_LOADING = 'SEMESTER_LOADING';
export const SEMESTER_FAILED = 'SEMESTER_FAILED';

export const ADD_INTERNSHIP = 'ADD_INTERNSHIP';
export const EDIT_INTERNSHIP = 'EDIT_INTERNSHIP';
export const DELETE_INTERNSHIP = 'ADD_INTERNSHIP';
export const INTERNSHIP_LOADING = 'INTERNSHIP_LOADING';
export const INTERNSHIP_FAILED = 'INTERNSHIP_FAILED';

export const ADD_COURSE = 'ADD_COURSE';
export const EDIT_COURSE = 'EDIT_COURSE';
export const DELETE_COURSE = 'ADD_COURSE';
export const COURSE_LOADING = 'COURSE_LOADING';
export const COURSE_FAILED = 'COURSE_FAILED';

export const ADD_RESULT = 'ADD_RESULT';
export const EDIT_RESULT = 'EDIT_RESULT';
export const DELETE_RESULT = 'ADD_RESULT';
export const RESULT_FAILED = 'RESULT_FAILED';
export const RESULT_LOADING = 'RESULT_LOADING';

export const ADD_ABSENCE = 'ADD_ABSENCE';
export const DELETE_ABSENCE = 'DELETE_ABSENCE';
export const ABSENCE_FAILED = 'ABSENCE_FAILED';
export const ABSENCE_LOADING = 'ABSENCE_LOADING';

export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const ACTIVITY_FAILED = 'ACTIVITY_FAILED';
export const ACTIVITY_LOADING = 'ACTIVITY_LOADING';

export const PROFILE_FAILED = 'PROFILE_FAILED';
export const PROFILE_LOADING = 'PROFILE_LOADING';

export const TEACHER_LOGIN_REQUEST = 'TEACHER_LOGIN_REQUEST';
export const TEACHER_LOGIN_SUCCESS = 'TEACHER_LOGIN_SUCCESS';
export const TEACHER_LOGIN_FAILURE = 'TEACHER_LOGIN_FAILURE';
export const TEACHER_LOGOUT_REQUEST = 'TEACHER_LOGOUT_REQUEST';
export const TEACHER_LOGOUT_SUCCESS = 'TEACHER_LOGOUT_SUCCESS';
export const TEACHER_LOGOUT_FAILURE = 'TEACHER_LOGOUT_FAILURE';

export const STUDENT_LOGIN_REQUEST = 'STUDENT_LOGIN_REQUEST';
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS';
export const STUDENT_LOGIN_FAILURE = 'STUDENT_LOGIN_FAILURE';
export const STUDENT_LOGOUT_REQUEST = 'STUDENT_LOGOUT_REQUEST';
export const STUDENT_LOGOUT_SUCCESS = 'STUDENT_LOGOUT_SUCCESS';
export const STUDENT_LOGOUT_FAILURE = 'STUDENT_LOGOUT_FAILURE';

export const REDIRECT = "REDIRECT";
export const REMOVE_REDIRECT = "REMOVE_REDIRECT";